#!/bin/bash

#setxkbmap -model 'macintosh' -layout 'us,ru' -variant ',' -option 'grp:win_menu_switch,grp_led:caps,compose:menu,lv3:ralt_switch,misc:typo,nbsp:level3'
nvidia-settings -l
touch $HOME/.dbus/Xdbus
chmod 600 $HOME/.dbus/Xdbus
env | grep DBUS_SESSION_BUS_ADDRESS > $HOME/.dbus/Xdbus
echo 'export DBUS_SESSION_BUS_ADDRESS' >> $HOME/.dbus/Xdbus

exit 0
