#!/usr/bin/perl

use strict;
use warnings;
use utf8;
use open qw/:encoding(UTF-8) :std/;
use POSIX;
use File::Spec;
use File::Find;
use Encode;

my (@deletedinbackup, $name, $nameo);
my $broot = '/media/backup';
my $log = '/home/assador/log/backup.log';
my @findintodelete = (
	'/media/backup/home',
	'/media/backup/media/data/Andrey',
	'/media/backup/media/data/Assador',
	'/media/backup/media/data/Archive',
	'/media/backup/media/data/Library',
	'/media/backup/media/data/Nia ou Veas',
	'/media/backup/media/data/Nia & Smallett',
	'/media/backup/media/data/Octopus',
	'/media/backup/media/data/Other',
	'/media/backup/media/data/Scrofa Tridens',
	'/media/backup/media/data/Temp/Necessary',
);
my @stuff = (
	'/home/assador/notes',
	'/home/assador/palettes',
	'/home/assador/scripts',
	'/media/data/Andrey',
	'/media/data/Assador',
	'/media/data/Archive',
	'/media/data/Library/3D/Objects/flask',
	'/media/data/Library/3D/Scenes',
	'/media/data/Library/Images/Other',
	'/media/data/Library/Images/Photo',
	'/media/data/Library/Images/Photo unsorted',
	'/media/data/Library/Literature',
	'/media/data/Library/Music/Video/Octopus - Концерт в Р-Клубе 23 января 2006 года.avi',
	'/media/data/Nia ou Veas',
	'/media/data/Nia & Smallett',
	'/media/data/Nina',
	'/media/data/Octopus',
	'/media/data/Other',
	'/media/data/Scrofa Tridens',
	'/media/data/Temp/Necessary',
);
my $list = "'" . join("' '", @stuff) . "'";
my $start = time;

sub wanted {
	$name = decode("UTF-8", File::Spec->rel2abs($File::Find::name));
	return if $name eq $broot;
	$nameo = substr($name, length($broot));
	if(!-f $nameo && !-d $nameo) {
		system("rm", -d $name ? "-rf" : "-f", $name);
		push(@deletedinbackup, $name);
	}
}

finddepth(\&wanted, @findintodelete);

print "Резервное копирование в $broot:\n";
`mkdir \'$broot\' 2> /dev/null`;
`cp -rfpdu --parents $list \'$broot\' | pv -t`;
sleep 3;
my $logtext = "Резервное копирование в $broot завершено.\n    Старт: "
	. strftime("%d.%m.%Y %H:%M:%S", localtime($start))
	. "\n    Финиш: "
	. strftime("%d.%m.%Y %H:%M:%S", localtime(time))
	. "\nУдалено устаревшее в резервной копии:\n    "
	. join("\n    ", @deletedinbackup)
	. "\nКопировалось:\n    "
	. join("\n    ", @stuff)
	. "\n";
print $logtext;
open(OUT, ">>:encoding(UTF-8)", $log) or die "Не могу записать лог в $log: $!\n";
$logtext = "-" x 80 . "\n" . $logtext if -f $log && -s $log > 0;
print OUT $logtext;
close(OUT);
print "Лог записан в $log\n";
exit 0;
