#!/usr/bin/perl

use strict;
use warnings;
use utf8;
use open qw/:encoding(UTF-8) :std/;
use POSIX;

my $key = 'Edha2Zf2NP';
my $source = '';
my $path = '/media/data/Temp/';
my @dow = ('Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота');
my %date;
my @sample = (
	'.*?b\-dl\-table__list[^<>]*>[^<>]*<[^<>]*>[^<>]*<[^<>]*>\s*([1-6]).*?b\-dl\-td_column[^<>]*>[^<>]*<[^<>]*>\s*([^<>]+).*?b\-dl\-td\-hw\-section[^<>]*>[^<>]*<[^<>]*>\s*([^<>]+)\s*<'
);
my @replace = (
	'<tr><td>$1\.<\/td><td>$2<\/td><td>$3<\/td><\/tr>$key'
);

sub setent {
	my $text = shift;
	my $ret = $text;
	my $pos;
	for(my $c = 0; $c < scalar @sample; $c++) {
		$text = $ret;
		$ret = "";
		$pos = 0;
		my $s = $sample[$c];
		my $r = $replace[$c];
		$s =~ s/\\(\d+)/'\\'.($1+1)/ge;
		$r =~ s/\$(\d+)/'".$'.($1+1).'."'/ge;
		$r = '"'.$r.'"';
		while($text =~ m/(.*?)$s/gsmix) {
			$pos = pos($text);
			$ret .= $1 . (eval $r);
		}
		$ret .= substr($text, $pos);
	}
	return $ret;
}

unless(@ARGV && $ARGV[0] =~ /^[1-6]$/) {die "Некорректный номер дня недели.\n";}
while(<STDIN>) {$source .= $_;}
$source =~ m/\bb-calendar\b.*?\b(\d{4})\b/is;
$date{y} = $1;
$source =~ s/.*$dow[$ARGV[0] - 1]//is;
$source =~ m/\bb-diary-date\b.*?(\d+)\.(\d+)/is;
$date{d} = $1; $date{m} = $2;
$source =~ s/${\($ARGV[0] == 6 ? '\/timetables' : $dow[$ARGV[0]])}.*//is;
$source = &setent($source);
$source =~ s/(.*)$key.*?$/$1/s;
$source =~ s/$key//gs;
$source = "<!DOCTYPE html><html><head><meta charset=\"utf-8\" /><title>ДЗ — $dow[$ARGV[0] - 1], $date{d}.$date{m}.$date{y}</title><style type=\"text/css\">table {border-collapse: collapse; border-spacing: 0; border-top: 1px solid #cccccc;} td {padding: 0.1em 0.9em 0.3em 0.9em; border-bottom: 1px solid #cccccc; vertical-align: top;} td:nth-child(1) {text-align: right;} td:nth-child(2) {font-weight: bold; white-space: nowrap;}</style></head><body><h1>$dow[$ARGV[0] - 1]<span style=\"font-weight: normal;\"> — $date{d}.$date{m}.$date{y}</span></h1><table>" . $source . "</table></body></html>\n";
$path = $path . "hw_" . $date{y} . "_" . $date{m} . "_" . $date{d} . ".htm";
open(OUT, ">:encoding(utf8)", $path) or die "Не могу создать $path: $!\n";
print OUT $source;
close(OUT);
`sensible-browser $path`;
exit 0;
