#!/bin/bash

while getopts "f:" opt; do
	case "$opt" in 
		f) result="$OPTARG"; shift 2;;
	esac
done
if [ -z "$result" ]; then
	result="/tmp/printfrombrowser.htm"
fi
if [ -f "$result" ]; then
	rm "$result"
fi
touch "$result"
for file in "$@"; do
	cat "$file" >> "$result"
done
sensible-browser "$result"

exit 0
