#!/usr/bin/perl

#	Заливка всего экрана сплошным цветом.

use strict;
use warnings;
use utf8;
use open qw/:encoding(UTF-8) :std/;
use Gtk3 "-init";

my @rgba = (1, 1, 1, 1);
my $window = Gtk3::Window->new;
$window->signal_connect(destroy => sub {Gtk3->main_quit;});
$window->signal_connect(key_release_event => \&key_release);
$window->set_decorated(0);
$window->maximize;
$window->fullscreen;
$window->set_visual($window->get_screen->get_rgba_visual);
my $da = Gtk3::DrawingArea->new;
$da->signal_connect(draw => \&fill, \@rgba);
$window->add($da);
$window->show_all;
Gtk3->main;

sub fill {
	my ($widget, $context, $data) = @_;
	$context->set_operator("clear");
	$context->paint;
	$context->set_operator("over");
	$context->set_source_rgba($data->[0], $data->[1], $data->[2], $data->[3]);
	$context->paint;
	return 0;
}
sub key_release {
	my (undef, $event) = @_;
	my $key = Gtk3::Gdk::keyval_name($event->keyval);
	exit if $key eq "Escape";
	if ($key eq "d") {$window->unfullscreen;}
	if ($key eq "f") {$window->fullscreen;}
	if ($key eq "1") {@rgba = (1, 1, 1, 1); $da->queue_draw();}
	if ($key eq "2") {@rgba = (0, 0, 0, 1); $da->queue_draw();}
	if ($key eq "3") {@rgba = (0.5, 0.5, 0.5, 1); $da->queue_draw();}
	if ($key eq "4") {@rgba = (1, 0, 0, 1); $da->queue_draw();}
	if ($key eq "5") {@rgba = (0, 1, 0, 1); $da->queue_draw();}
	if ($key eq "6") {@rgba = (0, 0, 1, 1); $da->queue_draw();}
	if ($key eq "7") {@rgba = (1, 1, 0, 1); $da->queue_draw();}
	if ($key eq "8") {@rgba = (1, 0, 1, 1); $da->queue_draw();}
	if ($key eq "9") {@rgba = (0, 1, 1, 1); $da->queue_draw();}
	return 0;
}

exit 0;
