#!/bin/bash

#	ds-translate [<text> [[<source language>] <target language>]]
#	if source missing, use auto'
#	if target missing, use DEFAULT_TARGET_LANG
#	if text missing, use xclip -o

DEFAULT_TARGET_LANG=ru
if [[ $3 ]]; then
	source="$2-"
	target="$3"
elif [[ $2 ]]; then
	source=""
	target="$2"
else
	source=""
	target="$DEFAULT_TARGET_LANG"
fi
if [[ $1 && ("$1" != "X") ]]; then
	text="$1"
else
	text=$(xclip -o | xargs -0)
fi
if [[ $text =~ ^(.*)\|[[:space:]]*([^[:space:]|>]*)[[:space:]]*\>[[:space:]]*([^[:space:]|>]*)[[:space:]]*$ ]]; then
	if [[ ${BASH_REMATCH[1]} ]]; then
		text="${BASH_REMATCH[1]}"
	fi
	if [[ ${BASH_REMATCH[2]} ]]; then
		source="${BASH_REMATCH[2]}"
	fi
	if [[ ${BASH_REMATCH[3]} ]]; then
		target="${BASH_REMATCH[3]}"
	fi
fi
result=$(curl -s -d "lang=$source$target" --data-urlencode "text=$text" https://translate.yandex.net/api/v1.5/tr.json/translate?key=trnsl.1.1.20160914T111341Z.8b4b9bd96181e074.fcd3840224709e84c20ac6400e11e98fe4be530e)
result=$(perl -0pe 's/^.*"\s*text\s*"\s*:\s*\[\s*"\s*([^"]*).*$/\1/si' <<<"$result")
echo "$result" | tr -d "\012" | ds-textfield
exit 0
