#!/usr/bin/perl

use strict;
use warnings;
use utf8;
use open qw/:encoding(UTF-8) :std/;
use POSIX;

my $source = "";

my @sample = (
#	'<span[^<>]*>\s*<img[^<>]*src=\"assets.*?</span>\s*</span>',
#	'<table>',
#	'^(\d+)_(\d+)_(\d+)_([^\n\r]*)$',
	'<table.*?<tr.*?<tr>(.*?)</tr>.*?\/table>',
	'(?:<\/?p>\s*){0,}<(\/?)td>(?:\s*<\/?p>){0,}',
);
my @replace = (
#	'',
#	'<h2>Технические\ характеристики<\/h2><table\ class\=\"border0\ zebrine\">',
#	'<div\ class\=\"object_imagealbum\ col-3\ col-lg-4\ col-md-6\ col-sm-12\ col-xs-12\"><div\ class\=\"block_01\ imagefile\"><a\ class\=\"colorbox\"\ href\=\"\/sites\/default\/files\/image\/2017_08\/$1_$2_$3_$4\"><img\ alt\=\"Сплав\ по Карелии,\ $3\.$2\.$1\"\ class\=\"border1\"\ src\=\"\/sites\/default\/files\/styles\/small\/public\/image\/2017_08\/$1_$2_$3_$4\"\ \/><\/a><\/div><\/div>',
	'<ul>$1</ul>',
	'<$1li>',
);

sub setent {
	my $text = shift;
	my $ret = $text;
	my $pos;
	for(my $c = 0; $c < scalar @sample; $c++) {
		$text = $ret;
		$ret = "";
		$pos = 0;
		my $s = $sample[$c];
		my $r = $replace[$c];
		$s =~ s/\\(\d+)/'\\'.($1+1)/ge;
		$r =~ s/\$(\d+)/'".$'.($1+1).'."'/ge;
		$r = '"'.$r.'"';
		while($text =~ m/(.*?)$s/gsmix) {
			$pos = pos($text);
			$ret .= $1 . (eval $r);
		}
		$ret .= substr($text, $pos);
	}
	return $ret;
}

while(<STDIN>) {$source .= $_;}
$source = &setent($source);
#$source =~ s/(.*)/<div\ class=\"row_01\ margin_bottom\">$1<\/div>/s;
print $source;
exit 0;
