#!/bin/bash

xfce4-terminal -T "Working 1" --working-directory="$1" -x bash -ic ". ds-venvex '$1' '$2' && cd '$1' && workon '$2' && ./manage.py runserver" && ds-wm -c "0, 1.0" -s "0.2 x -0.25" && wmctrl -r :ACTIVE: -t 0
xfce4-terminal -T "Working 2" --working-directory="$1" && ds-wm -c "0.2, 1.0" -s "0.3 x -0.25" && wmctrl -r :ACTIVE: -t 0
sleep 1
sensible-browser http://localhost:8000/admin > /dev/null 2>&1 && ds-wm -c "0, 0" -s "0.5 x 0.75" && wmctrl -r :ACTIVE: -t 0
cd "$1"
geany -is *.geany > /dev/null 2>&1 &
sleep 1
ds-wm -c "1.0, 0" -s "-0.5 x 1.0" && wmctrl -r :ACTIVE: -t 0
wmctrl -s 0

exit 0
